/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsThemeIndexRouteImport } from './routes/settings/theme/index'
import { Route as SettingsVoiceDevicesRouteImport } from './routes/settings/voice/devices'
import { Route as SettingsAccountSecurityRouteImport } from './routes/settings/account/security'
import { Route as SettingsAccountProfileRouteImport } from './routes/settings/account/profile'
import { Route as AuthenticatedChannelAtmeRouteImport } from './routes/_authenticated/channel/@me'
import { Route as AuthenticatedChannelChannelIdRouteImport } from './routes/_authenticated/channel/$channelId'
import { Route as AuthenticatedChannelGuildIdChar123ChannelIdChar125RouteImport } from './routes/_authenticated/channel/$guildId/{-$channelId}'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsThemeIndexRoute = SettingsThemeIndexRouteImport.update({
  id: '/theme/',
  path: '/theme/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsVoiceDevicesRoute = SettingsVoiceDevicesRouteImport.update({
  id: '/voice/devices',
  path: '/voice/devices',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountSecurityRoute = SettingsAccountSecurityRouteImport.update({
  id: '/account/security',
  path: '/account/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountProfileRoute = SettingsAccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const AuthenticatedChannelAtmeRoute =
  AuthenticatedChannelAtmeRouteImport.update({
    id: '/_authenticated/channel/@me',
    path: '/channel/@me',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedChannelChannelIdRoute =
  AuthenticatedChannelChannelIdRouteImport.update({
    id: '/_authenticated/channel/$channelId',
    path: '/channel/$channelId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedChannelGuildIdChar123ChannelIdChar125Route =
  AuthenticatedChannelGuildIdChar123ChannelIdChar125RouteImport.update({
    id: '/_authenticated/channel/$guildId/{-$channelId}',
    path: '/channel/$guildId/{-$channelId}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/channel/$channelId': typeof AuthenticatedChannelChannelIdRoute
  '/channel/@me': typeof AuthenticatedChannelAtmeRoute
  '/settings/account/profile': typeof SettingsAccountProfileRoute
  '/settings/account/security': typeof SettingsAccountSecurityRoute
  '/settings/voice/devices': typeof SettingsVoiceDevicesRoute
  '/settings/theme': typeof SettingsThemeIndexRoute
  '/channel/$guildId/{-$channelId}': typeof AuthenticatedChannelGuildIdChar123ChannelIdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/channel/$channelId': typeof AuthenticatedChannelChannelIdRoute
  '/channel/@me': typeof AuthenticatedChannelAtmeRoute
  '/settings/account/profile': typeof SettingsAccountProfileRoute
  '/settings/account/security': typeof SettingsAccountSecurityRoute
  '/settings/voice/devices': typeof SettingsVoiceDevicesRoute
  '/settings/theme': typeof SettingsThemeIndexRoute
  '/channel/$guildId/{-$channelId}': typeof AuthenticatedChannelGuildIdChar123ChannelIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/_authenticated/channel/$channelId': typeof AuthenticatedChannelChannelIdRoute
  '/_authenticated/channel/@me': typeof AuthenticatedChannelAtmeRoute
  '/settings/account/profile': typeof SettingsAccountProfileRoute
  '/settings/account/security': typeof SettingsAccountSecurityRoute
  '/settings/voice/devices': typeof SettingsVoiceDevicesRoute
  '/settings/theme/': typeof SettingsThemeIndexRoute
  '/_authenticated/channel/$guildId/{-$channelId}': typeof AuthenticatedChannelGuildIdChar123ChannelIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/channel/$channelId'
    | '/channel/@me'
    | '/settings/account/profile'
    | '/settings/account/security'
    | '/settings/voice/devices'
    | '/settings/theme'
    | '/channel/$guildId/{-$channelId}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/channel/$channelId'
    | '/channel/@me'
    | '/settings/account/profile'
    | '/settings/account/security'
    | '/settings/voice/devices'
    | '/settings/theme'
    | '/channel/$guildId/{-$channelId}'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/_authenticated/channel/$channelId'
    | '/_authenticated/channel/@me'
    | '/settings/account/profile'
    | '/settings/account/security'
    | '/settings/voice/devices'
    | '/settings/theme/'
    | '/_authenticated/channel/$guildId/{-$channelId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  AuthenticatedChannelChannelIdRoute: typeof AuthenticatedChannelChannelIdRoute
  AuthenticatedChannelAtmeRoute: typeof AuthenticatedChannelAtmeRoute
  AuthenticatedChannelGuildIdChar123ChannelIdChar125Route: typeof AuthenticatedChannelGuildIdChar123ChannelIdChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/theme/': {
      id: '/settings/theme/'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/voice/devices': {
      id: '/settings/voice/devices'
      path: '/voice/devices'
      fullPath: '/settings/voice/devices'
      preLoaderRoute: typeof SettingsVoiceDevicesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account/security': {
      id: '/settings/account/security'
      path: '/account/security'
      fullPath: '/settings/account/security'
      preLoaderRoute: typeof SettingsAccountSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account/profile': {
      id: '/settings/account/profile'
      path: '/account/profile'
      fullPath: '/settings/account/profile'
      preLoaderRoute: typeof SettingsAccountProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/channel/@me': {
      id: '/_authenticated/channel/@me'
      path: '/channel/@me'
      fullPath: '/channel/@me'
      preLoaderRoute: typeof AuthenticatedChannelAtmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/channel/$channelId': {
      id: '/_authenticated/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof AuthenticatedChannelChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/channel/$guildId/{-$channelId}': {
      id: '/_authenticated/channel/$guildId/{-$channelId}'
      path: '/channel/$guildId/{-$channelId}'
      fullPath: '/channel/$guildId/{-$channelId}'
      preLoaderRoute: typeof AuthenticatedChannelGuildIdChar123ChannelIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAccountProfileRoute: typeof SettingsAccountProfileRoute
  SettingsAccountSecurityRoute: typeof SettingsAccountSecurityRoute
  SettingsVoiceDevicesRoute: typeof SettingsVoiceDevicesRoute
  SettingsThemeIndexRoute: typeof SettingsThemeIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountProfileRoute: SettingsAccountProfileRoute,
  SettingsAccountSecurityRoute: SettingsAccountSecurityRoute,
  SettingsVoiceDevicesRoute: SettingsVoiceDevicesRoute,
  SettingsThemeIndexRoute: SettingsThemeIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRouteWithChildren,
  AuthenticatedChannelChannelIdRoute: AuthenticatedChannelChannelIdRoute,
  AuthenticatedChannelAtmeRoute: AuthenticatedChannelAtmeRoute,
  AuthenticatedChannelGuildIdChar123ChannelIdChar125Route:
    AuthenticatedChannelGuildIdChar123ChannelIdChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
