/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedChannelRouteImport } from './routes/_authenticated/channel'
import { Route as AuthenticatedChannelAtmeRouteImport } from './routes/_authenticated/channel/@me'
import { Route as AuthenticatedChannelChannelIdRouteImport } from './routes/_authenticated/channel/$channelId'
import { Route as AuthenticatedSettingsVoiceDevicesRouteImport } from './routes/_authenticated/settings/voice/devices'
import { Route as AuthenticatedSettingsGuildGuildIdRouteImport } from './routes/_authenticated/settings/guild/$guildId'
import { Route as AuthenticatedSettingsAppThemeRouteImport } from './routes/_authenticated/settings/app/theme'
import { Route as AuthenticatedSettingsAppNotificationsRouteImport } from './routes/_authenticated/settings/app/notifications'
import { Route as AuthenticatedSettingsAccountSecurityRouteImport } from './routes/_authenticated/settings/account/security'
import { Route as AuthenticatedSettingsAccountProfileRouteImport } from './routes/_authenticated/settings/account/profile'
import { Route as AuthenticatedChannelGuildIdChannelIdIndexRouteImport } from './routes/_authenticated/channel/$guildId/$channelId/index'
import { Route as AuthenticatedChannelGuildIdChannelIdMessageIdRouteImport } from './routes/_authenticated/channel/$guildId/$channelId/$messageId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChannelRoute = AuthenticatedChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChannelAtmeRoute =
  AuthenticatedChannelAtmeRouteImport.update({
    id: '/@me',
    path: '/@me',
    getParentRoute: () => AuthenticatedChannelRoute,
  } as any)
const AuthenticatedChannelChannelIdRoute =
  AuthenticatedChannelChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => AuthenticatedChannelRoute,
  } as any)
const AuthenticatedSettingsVoiceDevicesRoute =
  AuthenticatedSettingsVoiceDevicesRouteImport.update({
    id: '/voice/devices',
    path: '/voice/devices',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGuildGuildIdRoute =
  AuthenticatedSettingsGuildGuildIdRouteImport.update({
    id: '/guild/$guildId',
    path: '/guild/$guildId',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAppThemeRoute =
  AuthenticatedSettingsAppThemeRouteImport.update({
    id: '/app/theme',
    path: '/app/theme',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAppNotificationsRoute =
  AuthenticatedSettingsAppNotificationsRouteImport.update({
    id: '/app/notifications',
    path: '/app/notifications',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAccountSecurityRoute =
  AuthenticatedSettingsAccountSecurityRouteImport.update({
    id: '/account/security',
    path: '/account/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAccountProfileRoute =
  AuthenticatedSettingsAccountProfileRouteImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedChannelGuildIdChannelIdIndexRoute =
  AuthenticatedChannelGuildIdChannelIdIndexRouteImport.update({
    id: '/$guildId/$channelId/',
    path: '/$guildId/$channelId/',
    getParentRoute: () => AuthenticatedChannelRoute,
  } as any)
const AuthenticatedChannelGuildIdChannelIdMessageIdRoute =
  AuthenticatedChannelGuildIdChannelIdMessageIdRouteImport.update({
    id: '/$guildId/$channelId/$messageId',
    path: '/$guildId/$channelId/$messageId',
    getParentRoute: () => AuthenticatedChannelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/channel': typeof AuthenticatedChannelRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/channel/$channelId': typeof AuthenticatedChannelChannelIdRoute
  '/channel/@me': typeof AuthenticatedChannelAtmeRoute
  '/settings/account/profile': typeof AuthenticatedSettingsAccountProfileRoute
  '/settings/account/security': typeof AuthenticatedSettingsAccountSecurityRoute
  '/settings/app/notifications': typeof AuthenticatedSettingsAppNotificationsRoute
  '/settings/app/theme': typeof AuthenticatedSettingsAppThemeRoute
  '/settings/guild/$guildId': typeof AuthenticatedSettingsGuildGuildIdRoute
  '/settings/voice/devices': typeof AuthenticatedSettingsVoiceDevicesRoute
  '/channel/$guildId/$channelId/$messageId': typeof AuthenticatedChannelGuildIdChannelIdMessageIdRoute
  '/channel/$guildId/$channelId/': typeof AuthenticatedChannelGuildIdChannelIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/channel': typeof AuthenticatedChannelRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/channel/$channelId': typeof AuthenticatedChannelChannelIdRoute
  '/channel/@me': typeof AuthenticatedChannelAtmeRoute
  '/settings/account/profile': typeof AuthenticatedSettingsAccountProfileRoute
  '/settings/account/security': typeof AuthenticatedSettingsAccountSecurityRoute
  '/settings/app/notifications': typeof AuthenticatedSettingsAppNotificationsRoute
  '/settings/app/theme': typeof AuthenticatedSettingsAppThemeRoute
  '/settings/guild/$guildId': typeof AuthenticatedSettingsGuildGuildIdRoute
  '/settings/voice/devices': typeof AuthenticatedSettingsVoiceDevicesRoute
  '/channel/$guildId/$channelId/$messageId': typeof AuthenticatedChannelGuildIdChannelIdMessageIdRoute
  '/channel/$guildId/$channelId': typeof AuthenticatedChannelGuildIdChannelIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/channel': typeof AuthenticatedChannelRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/channel/$channelId': typeof AuthenticatedChannelChannelIdRoute
  '/_authenticated/channel/@me': typeof AuthenticatedChannelAtmeRoute
  '/_authenticated/settings/account/profile': typeof AuthenticatedSettingsAccountProfileRoute
  '/_authenticated/settings/account/security': typeof AuthenticatedSettingsAccountSecurityRoute
  '/_authenticated/settings/app/notifications': typeof AuthenticatedSettingsAppNotificationsRoute
  '/_authenticated/settings/app/theme': typeof AuthenticatedSettingsAppThemeRoute
  '/_authenticated/settings/guild/$guildId': typeof AuthenticatedSettingsGuildGuildIdRoute
  '/_authenticated/settings/voice/devices': typeof AuthenticatedSettingsVoiceDevicesRoute
  '/_authenticated/channel/$guildId/$channelId/$messageId': typeof AuthenticatedChannelGuildIdChannelIdMessageIdRoute
  '/_authenticated/channel/$guildId/$channelId/': typeof AuthenticatedChannelGuildIdChannelIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/channel'
    | '/settings'
    | '/channel/$channelId'
    | '/channel/@me'
    | '/settings/account/profile'
    | '/settings/account/security'
    | '/settings/app/notifications'
    | '/settings/app/theme'
    | '/settings/guild/$guildId'
    | '/settings/voice/devices'
    | '/channel/$guildId/$channelId/$messageId'
    | '/channel/$guildId/$channelId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/channel'
    | '/settings'
    | '/channel/$channelId'
    | '/channel/@me'
    | '/settings/account/profile'
    | '/settings/account/security'
    | '/settings/app/notifications'
    | '/settings/app/theme'
    | '/settings/guild/$guildId'
    | '/settings/voice/devices'
    | '/channel/$guildId/$channelId/$messageId'
    | '/channel/$guildId/$channelId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/channel'
    | '/_authenticated/settings'
    | '/_authenticated/channel/$channelId'
    | '/_authenticated/channel/@me'
    | '/_authenticated/settings/account/profile'
    | '/_authenticated/settings/account/security'
    | '/_authenticated/settings/app/notifications'
    | '/_authenticated/settings/app/theme'
    | '/_authenticated/settings/guild/$guildId'
    | '/_authenticated/settings/voice/devices'
    | '/_authenticated/channel/$guildId/$channelId/$messageId'
    | '/_authenticated/channel/$guildId/$channelId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channel': {
      id: '/_authenticated/channel'
      path: '/channel'
      fullPath: '/channel'
      preLoaderRoute: typeof AuthenticatedChannelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channel/@me': {
      id: '/_authenticated/channel/@me'
      path: '/@me'
      fullPath: '/channel/@me'
      preLoaderRoute: typeof AuthenticatedChannelAtmeRouteImport
      parentRoute: typeof AuthenticatedChannelRoute
    }
    '/_authenticated/channel/$channelId': {
      id: '/_authenticated/channel/$channelId'
      path: '/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof AuthenticatedChannelChannelIdRouteImport
      parentRoute: typeof AuthenticatedChannelRoute
    }
    '/_authenticated/settings/voice/devices': {
      id: '/_authenticated/settings/voice/devices'
      path: '/voice/devices'
      fullPath: '/settings/voice/devices'
      preLoaderRoute: typeof AuthenticatedSettingsVoiceDevicesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/guild/$guildId': {
      id: '/_authenticated/settings/guild/$guildId'
      path: '/guild/$guildId'
      fullPath: '/settings/guild/$guildId'
      preLoaderRoute: typeof AuthenticatedSettingsGuildGuildIdRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/app/theme': {
      id: '/_authenticated/settings/app/theme'
      path: '/app/theme'
      fullPath: '/settings/app/theme'
      preLoaderRoute: typeof AuthenticatedSettingsAppThemeRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/app/notifications': {
      id: '/_authenticated/settings/app/notifications'
      path: '/app/notifications'
      fullPath: '/settings/app/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/account/security': {
      id: '/_authenticated/settings/account/security'
      path: '/account/security'
      fullPath: '/settings/account/security'
      preLoaderRoute: typeof AuthenticatedSettingsAccountSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/account/profile': {
      id: '/_authenticated/settings/account/profile'
      path: '/account/profile'
      fullPath: '/settings/account/profile'
      preLoaderRoute: typeof AuthenticatedSettingsAccountProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/channel/$guildId/$channelId/': {
      id: '/_authenticated/channel/$guildId/$channelId/'
      path: '/$guildId/$channelId'
      fullPath: '/channel/$guildId/$channelId/'
      preLoaderRoute: typeof AuthenticatedChannelGuildIdChannelIdIndexRouteImport
      parentRoute: typeof AuthenticatedChannelRoute
    }
    '/_authenticated/channel/$guildId/$channelId/$messageId': {
      id: '/_authenticated/channel/$guildId/$channelId/$messageId'
      path: '/$guildId/$channelId/$messageId'
      fullPath: '/channel/$guildId/$channelId/$messageId'
      preLoaderRoute: typeof AuthenticatedChannelGuildIdChannelIdMessageIdRouteImport
      parentRoute: typeof AuthenticatedChannelRoute
    }
  }
}

interface AuthenticatedChannelRouteChildren {
  AuthenticatedChannelChannelIdRoute: typeof AuthenticatedChannelChannelIdRoute
  AuthenticatedChannelAtmeRoute: typeof AuthenticatedChannelAtmeRoute
  AuthenticatedChannelGuildIdChannelIdMessageIdRoute: typeof AuthenticatedChannelGuildIdChannelIdMessageIdRoute
  AuthenticatedChannelGuildIdChannelIdIndexRoute: typeof AuthenticatedChannelGuildIdChannelIdIndexRoute
}

const AuthenticatedChannelRouteChildren: AuthenticatedChannelRouteChildren = {
  AuthenticatedChannelChannelIdRoute: AuthenticatedChannelChannelIdRoute,
  AuthenticatedChannelAtmeRoute: AuthenticatedChannelAtmeRoute,
  AuthenticatedChannelGuildIdChannelIdMessageIdRoute:
    AuthenticatedChannelGuildIdChannelIdMessageIdRoute,
  AuthenticatedChannelGuildIdChannelIdIndexRoute:
    AuthenticatedChannelGuildIdChannelIdIndexRoute,
}

const AuthenticatedChannelRouteWithChildren =
  AuthenticatedChannelRoute._addFileChildren(AuthenticatedChannelRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountProfileRoute: typeof AuthenticatedSettingsAccountProfileRoute
  AuthenticatedSettingsAccountSecurityRoute: typeof AuthenticatedSettingsAccountSecurityRoute
  AuthenticatedSettingsAppNotificationsRoute: typeof AuthenticatedSettingsAppNotificationsRoute
  AuthenticatedSettingsAppThemeRoute: typeof AuthenticatedSettingsAppThemeRoute
  AuthenticatedSettingsGuildGuildIdRoute: typeof AuthenticatedSettingsGuildGuildIdRoute
  AuthenticatedSettingsVoiceDevicesRoute: typeof AuthenticatedSettingsVoiceDevicesRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountProfileRoute:
    AuthenticatedSettingsAccountProfileRoute,
  AuthenticatedSettingsAccountSecurityRoute:
    AuthenticatedSettingsAccountSecurityRoute,
  AuthenticatedSettingsAppNotificationsRoute:
    AuthenticatedSettingsAppNotificationsRoute,
  AuthenticatedSettingsAppThemeRoute: AuthenticatedSettingsAppThemeRoute,
  AuthenticatedSettingsGuildGuildIdRoute:
    AuthenticatedSettingsGuildGuildIdRoute,
  AuthenticatedSettingsVoiceDevicesRoute:
    AuthenticatedSettingsVoiceDevicesRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedChannelRoute: typeof AuthenticatedChannelRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChannelRoute: AuthenticatedChannelRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
