name: Build to GH Pages
on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                persist-credentials: false

            - uses: actions/setup-node@v4
              with:
                node-version: 23
                
            - name: build
              id: build
              run: |
                npm ci
                BASE_PATH="/shoot-client" npm run build
                
            - name: test
              id: test
              run: npm run test

            - name: Upload artifact
              id: deployment
              uses: actions/upload-pages-artifact@v3
              with:
                path: dist/
    
    deploy:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            pages: write
            id-token: write
        environment: 
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to pages
              id: deployment
              uses: actions/deploy-pages@v4